name: Sync to Azure DevOps

on:
  push:
    branches:
      - main  # أو بدّلها باسم البرانش ديالك

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "yassineouhadi99@gmail.com"
          git config --global user.name "Yasineert"

      - name: Add Azure remote and push
        run: |
          if git remote | grep -q '^azure$'; then
            git remote remove azure
          fi
          git remote add azure https://$AZURE_USERNAME:$AZURE_PAT@dev.azure.com/OTHMANIHASNA/transport-ai/_git/transport-ai
          git push azure --mirror
        env:
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          AZURE_PAT: ${{ secrets.AZURE_PAT }}
